name: "15 Params"

on:
  push:
    branches: test/pr-1763048673479-10
  workflow_dispatch:
    inputs:
      input_1:
        description: JSON of additional options
        type: string
        required: false
      input_2:
        description: JSON of additional options
        type: string
        required: false
      input_3:
        description: JSON of additional options
        type: string
        required: false
      input_4:
        description: JSON of additional options
        type: string
        required: false
      input_5:
        description: JSON of additional options
        type: string
        required: false
      input_6:
        description: JSON of additional options
        type: string
        required: false
      input_7:
        description: JSON of additional options
        type: string
        required: false
      input_8:
        description: JSON of additional options
        type: string
        required: false
      input_9:
        description: JSON of additional options
        type: string
        required: false
      input_10:
        description: JSON of additional options
        type: string
        required: false
      input_11:
        description: JSON of additional options
        type: string
        required: false
      input_12:
        description: 12
        type: string
        required: false


jobs:
  show-params:
    runs-on: ubuntu-latest

    steps:
      - name: Print parameters
        run: |
          echo '${{ inputs.additional_args }}' | jq .

          # Example: direct access
          echo "param3 = ${{ fromJson(inputs.additional_args).param3 }}"
